[package]
name = "wgsrv"
authors = ["Sven Willner <sven.willner@gmail.com>"]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
clap = { version = "4", features = ["derive"] }
futures = "0.3"
ipnetwork = { version = "0.21", features = ["serde"] }
itertools = "0.15"
log = "0.4"
rtnetlink = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
termion = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wireguard-control = "1"
